[colors.bright]
black = "#353539"
blue = "#b9aeda"
cyan = "#f591b2"
green = "#9dc6ac"
magenta = "#ecaad6"
red = "#ffae9f"
white = "#cac9dd"
yellow = "#f0c5a9"

[colors.cursor]
cursor = "#3dad97"
text = "#c9c7cd"

[colors.normal]
black = "#27272a"
blue = "#aca1cf"
cyan = "#ea83a5"
green = "#90b99f"
magenta = "#e29eca"
red = "#f5a191"
white = "#c1c0d4"
yellow = "#e6b99d"

[colors.primary]
background = "#11121a"
foreground = "#c9c7cd"

[env]
TERM = "xterm-256color"

[window]
opacity = 0.7
option_as_alt = "Both"
blur = true
dynamic_padding = false

[window.padding]
x = 12
y = 12

